import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../core/theme/study_reps_theme.dart';
import '../../data/services/engines/review_queue_service.dart';
import '../../data/services/engines/question_generation_engine.dart';
import '../../data/services/engines/flashcard_generation_engine.dart';
import '../../domain/models/video_model.dart';

/// Content Review Screen
///
/// The human-in-the-loop gate for all AI-generated questions and flashcards.
/// Content generated by [QuestionGenerationEngine] and [FlashcardGenerationEngine]
/// lands here as PENDING. You approve, reject, or edit each item.
/// Only APPROVED items are served in the Drill / Quiz / feed sections.
class ContentReviewScreen extends StatefulWidget {
  const ContentReviewScreen({super.key});

  static void show(BuildContext context) {
    Navigator.push(context, MaterialPageRoute(builder: (_) => const ContentReviewScreen()));
  }

  @override
  State<ContentReviewScreen> createState() => _ContentReviewScreenState();
}

class _ContentReviewScreenState extends State<ContentReviewScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  List<ReviewItem> _allItems = [];
  bool _isGenerating = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _refresh();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _refresh() => setState(() => _allItems = ReviewQueueService.getAll());

  List<ReviewItem> get _pending => _allItems.where((i) => i.status == ReviewStatus.pending).toList();
  List<ReviewItem> get _approved => _allItems.where((i) => i.status == ReviewStatus.approved).toList();
  List<ReviewItem> get _rejected => _allItems.where((i) => i.status == ReviewStatus.rejected).toList();

  @override
  Widget build(BuildContext context) {
    final stats = ReviewQueueService.stats;

    return Scaffold(
      backgroundColor: const Color(0xFF111111),
      appBar: AppBar(
        backgroundColor: const Color(0xFF1A1A1A),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_rounded, color: Colors.white, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Content Review',
                style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.w700, color: Colors.white)),
            Text('${stats['pending']} pending · ${stats['approved']} approved',
                style: GoogleFonts.outfit(fontSize: 12, color: Colors.white38)),
          ],
        ),
        actions: [
          // Generate button
          TextButton.icon(
            onPressed: _isGenerating ? null : _showGenerateDialog,
            icon: _isGenerating
                ? const SizedBox(width: 14, height: 14,
                    child: CircularProgressIndicator(strokeWidth: 2, color: StudyRepsTheme.warmOrange))
                : const Icon(Icons.auto_fix_high_rounded, size: 16, color: StudyRepsTheme.warmOrange),
            label: Text('Generate',
                style: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w600,
                    color: _isGenerating ? Colors.white24 : StudyRepsTheme.warmOrange)),
          ),
          const SizedBox(width: 8),
        ],
        bottom: TabBar(
          controller: _tabController,
          labelStyle: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w600),
          unselectedLabelStyle: GoogleFonts.outfit(fontSize: 13),
          labelColor: StudyRepsTheme.warmOrange,
          unselectedLabelColor: Colors.white38,
          indicatorColor: StudyRepsTheme.warmOrange,
          indicatorSize: TabBarIndicatorSize.label,
          tabs: [
            Tab(text: 'Pending (${_pending.length})'),
            Tab(text: 'Approved (${_approved.length})'),
            Tab(text: 'Rejected (${_rejected.length})'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildList(_pending, showActions: true),
          _buildList(_approved, showActions: false),
          _buildList(_rejected, showActions: false),
        ],
      ),
    );
  }

  Widget _buildList(List<ReviewItem> items, {required bool showActions}) {
    if (items.isEmpty) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.inbox_rounded, color: Colors.white12, size: 64),
            const SizedBox(height: 16),
            Text('Nothing here',
                style: GoogleFonts.outfit(fontSize: 18, color: Colors.white24)),
            const SizedBox(height: 8),
            if (showActions)
              Text('Tap Generate to create content for review',
                  style: GoogleFonts.outfit(fontSize: 13, color: Colors.white12)),
          ],
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 100),
      itemCount: items.length,
      itemBuilder: (context, i) => _ReviewCard(
        item: items[i],
        showActions: showActions,
        onApprove: () async {
          HapticFeedback.lightImpact();
          await ReviewQueueService.approve(items[i].id);
          _refresh();
        },
        onReject: () async {
          HapticFeedback.mediumImpact();
          await ReviewQueueService.reject(items[i].id);
          _refresh();
        },
        onDelete: () async {
          await ReviewQueueService.delete(items[i].id);
          _refresh();
        },
        onEdit: () => _showEditDialog(items[i]),
      ).animate().fadeIn(duration: 250.ms, delay: (i * 40).ms).slideY(begin: 0.04),
    );
  }

  // ── Generate Dialog ────────────────────────────────────────────────────────

  void _showGenerateDialog() {
    // For now, generate using a known video from the feed.
    // In the full version this would show a video picker.
    showDialog(
      context: context,
      builder: (ctx) => _GenerateDialog(
        onGenerate: (videoId, videoTitle, subject, transcript, types) async {
          Navigator.pop(ctx);
          setState(() => _isGenerating = true);

          // Build a minimal VideoModel from the inputs
          final mockVideo = VideoModel(
            id: videoId,
            title: videoTitle,
            subject: subject,
            transcript: transcript,
            videoUrl: '',
            creatorName: 'StudyReps',
            question: const QuestionModel(
              id: 'placeholder',
              prompt: '',
              correctAnswer: '',
              type: QuestionType.openInput,
            ),
          );

          try {
            if (types.contains('questions')) {
              await QuestionGenerationEngine.generateAndQueue(mockVideo);
            }
            if (types.contains('flashcards')) {
              await FlashcardGenerationEngine.generateAndQueue(mockVideo);
            }
          } catch (e) {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text('Generation error: $e'), backgroundColor: StudyRepsTheme.errorPink),
              );
            }
          } finally {
            if (mounted) {
              setState(() => _isGenerating = false);
              _refresh();
              _tabController.animateTo(0); // Jump to pending tab
            }
          }
        },
      ),
    );
  }

  // ── Edit Dialog ────────────────────────────────────────────────────────────

  void _showEditDialog(ReviewItem item) {
    final promptCtrl = TextEditingController(text: item.displayPrompt);
    final answerCtrl = TextEditingController(text: item.displayAnswer);

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: const Color(0xFF1E1E1E),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Text('Edit & Approve',
            style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.w700, color: Colors.white)),
        content: SizedBox(
          width: double.maxFinite,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _dialogField('Question / Front', promptCtrl, maxLines: 4),
              const SizedBox(height: 12),
              _dialogField('Answer / Back', answerCtrl, maxLines: 6),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: Text('Cancel', style: GoogleFonts.outfit(color: Colors.white38)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: StudyRepsTheme.warmOrange,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            onPressed: () async {
              // Update content fields
              item.content[item.type == ReviewItemType.question ? 'prompt' : 'front'] = promptCtrl.text;
              item.content[item.type == ReviewItemType.question ? 'correct_answer' : 'back'] = answerCtrl.text;
              await ReviewQueueService.approve(item.id, note: 'Manually edited before approval');
              await ReviewQueueService.updateItem(item);
              if (ctx.mounted) {
                Navigator.pop(ctx);
                _refresh();
              }
            },
            child: Text('Save & Approve',
                style: GoogleFonts.outfit(fontSize: 14, fontWeight: FontWeight.w700, color: Colors.white)),
          ),
        ],
      ),
    );
  }

  Widget _dialogField(String label, TextEditingController ctrl, {int maxLines = 1}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: GoogleFonts.outfit(fontSize: 12, color: Colors.white38)),
        const SizedBox(height: 6),
        TextField(
          controller: ctrl,
          maxLines: maxLines,
          style: GoogleFonts.outfit(fontSize: 14, color: Colors.white),
          decoration: InputDecoration(
            filled: true,
            fillColor: Colors.white.withOpacity(0.06),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.white.withOpacity(0.1)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.white.withOpacity(0.1)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: StudyRepsTheme.warmOrange),
            ),
          ),
        ),
      ],
    );
  }
}

// ─── Individual Review Card ───────────────────────────────────────────────────

class _ReviewCard extends StatelessWidget {
  final ReviewItem item;
  final bool showActions;
  final VoidCallback onApprove;
  final VoidCallback onReject;
  final VoidCallback onDelete;
  final VoidCallback onEdit;

  const _ReviewCard({
    required this.item,
    required this.showActions,
    required this.onApprove,
    required this.onReject,
    required this.onDelete,
    required this.onEdit,
  });

  Color get _typeColor => item.type == ReviewItemType.question
      ? const Color(0xFF6366F1)  // Indigo for questions
      : StudyRepsTheme.warmOrange; // Orange for flashcards

  String get _typeLabel => item.type == ReviewItemType.question ? 'QUESTION' : 'FLASHCARD';

  Color get _diffColor {
    switch (item.difficulty) {
      case 'easy': return StudyRepsTheme.warmGreen;
      case 'hard': return StudyRepsTheme.errorPink;
      default: return StudyRepsTheme.warmOrange;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        color: const Color(0xFF1A1A1A),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withOpacity(0.06)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header row
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 14, 12, 0),
            child: Row(
              children: [
                // Type chip
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: _typeColor.withOpacity(0.15),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(_typeLabel,
                      style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w700,
                          color: _typeColor, letterSpacing: 0.8)),
                ),
                const SizedBox(width: 8),
                // Bloom level or card label
                if (item.bloomLevel.isNotEmpty || item.cardLabel.isNotEmpty)
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: Colors.white.withOpacity(0.06),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(item.bloomLevel.isNotEmpty ? item.bloomLevel : item.cardLabel,
                        style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w600,
                            color: Colors.white54, letterSpacing: 0.5)),
                  ),
                const SizedBox(width: 8),
                // Difficulty
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: _diffColor.withOpacity(0.12),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(item.difficulty.toUpperCase(),
                      style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w700,
                          color: _diffColor, letterSpacing: 0.5)),
                ),
                const Spacer(),
                // Delete always visible
                GestureDetector(
                  onTap: onDelete,
                  child: const Icon(Icons.delete_outline_rounded, color: Colors.white24, size: 18),
                ),
              ],
            ),
          ),

          // Video source
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
            child: Text('📹 ${item.videoTitle}',
                style: GoogleFonts.outfit(fontSize: 11, color: Colors.white24),
                maxLines: 1, overflow: TextOverflow.ellipsis),
          ),

          const Divider(color: Colors.white10, height: 20),

          // Question / Front
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item.type == ReviewItemType.question ? 'QUESTION' : 'FRONT',
                    style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w700,
                        color: Colors.white24, letterSpacing: 1)),
                const SizedBox(height: 6),
                Text(item.displayPrompt,
                    style: GoogleFonts.outfit(fontSize: 15, fontWeight: FontWeight.w600,
                        color: Colors.white, height: 1.5)),
              ],
            ),
          ),

          const SizedBox(height: 14),

          // Answer / Back
          Container(
            margin: const EdgeInsets.symmetric(horizontal: 16),
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: _typeColor.withOpacity(0.06),
              borderRadius: BorderRadius.circular(14),
              border: Border.all(color: _typeColor.withOpacity(0.12)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item.type == ReviewItemType.question ? 'MODEL ANSWER' : 'BACK',
                    style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w700,
                        color: _typeColor.withOpacity(0.7), letterSpacing: 1)),
                const SizedBox(height: 6),
                Text(item.displayAnswer,
                    style: GoogleFonts.outfit(fontSize: 13, color: Colors.white70, height: 1.5)),
              ],
            ),
          ),

          // Explanation / memory hook if present
          if (item.explanation.isNotEmpty) ...[
            const SizedBox(height: 10),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('💡', style: TextStyle(fontSize: 12)),
                  const SizedBox(width: 6),
                  Expanded(
                    child: Text(item.explanation,
                        style: GoogleFonts.outfit(fontSize: 12, color: Colors.white38, height: 1.4,
                            fontStyle: FontStyle.italic)),
                  ),
                ],
              ),
            ),
          ],

          const SizedBox(height: 16),

          // Action row
          if (showActions)
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              child: Row(
                children: [
                  // Edit & Approve
                  Expanded(
                    child: GestureDetector(
                      onTap: onEdit,
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 11),
                        decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.06),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: Colors.white12),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(Icons.edit_rounded, size: 14, color: Colors.white54),
                            const SizedBox(width: 6),
                            Text('Edit',
                                style: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w600,
                                    color: Colors.white54)),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  // Reject
                  GestureDetector(
                    onTap: onReject,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 11),
                      decoration: BoxDecoration(
                        color: StudyRepsTheme.errorPink.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: StudyRepsTheme.errorPink.withOpacity(0.3)),
                      ),
                      child: const Icon(Icons.close_rounded, size: 18, color: StudyRepsTheme.errorPink),
                    ),
                  ),
                  const SizedBox(width: 8),
                  // Approve ✓
                  GestureDetector(
                    onTap: onApprove,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 11),
                      decoration: BoxDecoration(
                        color: StudyRepsTheme.warmGreen.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: StudyRepsTheme.warmGreen.withOpacity(0.3)),
                      ),
                      child: const Icon(Icons.check_rounded, size: 18, color: StudyRepsTheme.warmGreen),
                    ),
                  ),
                ],
              ),
            )
          else
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
              child: Row(
                children: [
                  Icon(
                    item.status == ReviewStatus.approved
                        ? Icons.check_circle_rounded
                        : Icons.cancel_rounded,
                    size: 14,
                    color: item.status == ReviewStatus.approved
                        ? StudyRepsTheme.warmGreen
                        : StudyRepsTheme.errorPink,
                  ),
                  const SizedBox(width: 6),
                  Text(
                    item.status == ReviewStatus.approved ? 'Approved' : 'Rejected',
                    style: GoogleFonts.outfit(
                      fontSize: 12, fontWeight: FontWeight.w600,
                      color: item.status == ReviewStatus.approved
                          ? StudyRepsTheme.warmGreen
                          : StudyRepsTheme.errorPink,
                    ),
                  ),
                  if (item.reviewNote != null) ...[
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text('· ${item.reviewNote}',
                          style: GoogleFonts.outfit(fontSize: 11, color: Colors.white24),
                          maxLines: 1, overflow: TextOverflow.ellipsis),
                    ),
                  ],
                ],
              ),
            ),
        ],
      ),
    );
  }
}

// ─── Generate Dialog ──────────────────────────────────────────────────────────

class _GenerateDialog extends StatefulWidget {
  final Function(String id, String title, String subject, String transcript, List<String> types) onGenerate;

  const _GenerateDialog({required this.onGenerate});

  @override
  State<_GenerateDialog> createState() => _GenerateDialogState();
}

class _GenerateDialogState extends State<_GenerateDialog> {
  final _titleCtrl = TextEditingController();
  final _subjectCtrl = TextEditingController();
  final _transcriptCtrl = TextEditingController();
  bool _genQuestions = true;
  bool _genFlashcards = true;

  @override
  void dispose() {
    _titleCtrl.dispose();
    _subjectCtrl.dispose();
    _transcriptCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      title: Text('Generate Content',
          style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.w700, color: Colors.white)),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Paste the video title, subject, and as much transcript text as possible. '
                  'More context = better questions.',
                  style: GoogleFonts.outfit(fontSize: 12, color: Colors.white38, height: 1.5)),
              const SizedBox(height: 16),
              _field('Video Title *', _titleCtrl),
              const SizedBox(height: 10),
              _field('Subject *', _subjectCtrl, hint: 'e.g. Physics, Chemistry, Mathematics'),
              const SizedBox(height: 10),
              _field('Transcript / Notes (optional but recommended)',
                  _transcriptCtrl, maxLines: 6,
                  hint: 'Paste the video transcript or your own notes here...'),
              const SizedBox(height: 16),
              Text('Generate:', style: GoogleFonts.outfit(fontSize: 13, color: Colors.white54)),
              const SizedBox(height: 8),
              Row(
                children: [
                  _toggle('Questions', _genQuestions,
                      (v) => setState(() => _genQuestions = v), const Color(0xFF6366F1)),
                  const SizedBox(width: 10),
                  _toggle('Flashcards', _genFlashcards,
                      (v) => setState(() => _genFlashcards = v), StudyRepsTheme.warmOrange),
                ],
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text('Cancel', style: GoogleFonts.outfit(color: Colors.white38)),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: StudyRepsTheme.warmOrange,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          onPressed: () {
            if (_titleCtrl.text.trim().isEmpty || _subjectCtrl.text.trim().isEmpty) return;
            if (!_genQuestions && !_genFlashcards) return;
            final types = [
              if (_genQuestions) 'questions',
              if (_genFlashcards) 'flashcards',
            ];
            Navigator.pop(context);
            widget.onGenerate(
              'custom_${DateTime.now().millisecondsSinceEpoch}',
              _titleCtrl.text.trim(),
              _subjectCtrl.text.trim(),
              _transcriptCtrl.text.trim(),
              types,
            );
          },
          child: Text('Generate',
              style: GoogleFonts.outfit(fontSize: 14, fontWeight: FontWeight.w700, color: Colors.white)),
        ),
      ],
    );
  }

  Widget _field(String label, TextEditingController ctrl, {int maxLines = 1, String? hint}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: GoogleFonts.outfit(fontSize: 12, color: Colors.white38)),
        const SizedBox(height: 6),
        TextField(
          controller: ctrl,
          maxLines: maxLines,
          style: GoogleFonts.outfit(fontSize: 14, color: Colors.white),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: GoogleFonts.outfit(fontSize: 13, color: Colors.white24),
            filled: true,
            fillColor: Colors.white.withOpacity(0.06),
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: Colors.white.withOpacity(0.1))),
            enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: Colors.white.withOpacity(0.1))),
            focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: StudyRepsTheme.warmOrange)),
          ),
        ),
      ],
    );
  }

  Widget _toggle(String label, bool value, ValueChanged<bool> onChanged, Color color) {
    return GestureDetector(
      onTap: () => onChanged(!value),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        decoration: BoxDecoration(
          color: value ? color.withOpacity(0.15) : Colors.white.withOpacity(0.04),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: value ? color.withOpacity(0.4) : Colors.white.withOpacity(0.08)),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(value ? Icons.check_box_rounded : Icons.check_box_outline_blank_rounded,
                color: value ? color : Colors.white24, size: 16),
            const SizedBox(width: 6),
            Text(label,
                style: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w600,
                    color: value ? color : Colors.white38)),
          ],
        ),
      ),
    );
  }
}
