-- StudyReps Phase 1: Seed 20 Educational Videos
-- Paste this into Supabase Dashboard > SQL Editor > New Query > Run

INSERT INTO educational_content (id, title, subject, "videoUrl", "lockTimestamp", "creatorName", "difficultyLevel", "topicId", "conceptCluster", tags, language, question)
VALUES
-- PHYSICS (4 new)
('physics_newtons_laws', 'Newton''s 3 Laws of Motion', 'Physics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 12, 'PhysicsWallah', 1, 'classical_mechanics', 'newton_laws', '["physics","newton","motion","laws"]', 'en', '{"id":"q_newton_laws_1","prompt":"Which of Newton''s laws states that F = ma?","correctAnswer":"Second Law","type":"multiple_choice","options":["First Law","Second Law","Third Law","Law of Gravitation"],"hint":"Force equals mass times acceleration","explanation":"Newton''s Second Law relates force, mass, and acceleration: F = ma."}'),

('physics_projectile', 'Projectile Motion Explained', 'Physics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 15, 'ScienceGuy', 2, 'classical_mechanics', 'kinematics', '["physics","projectile","motion","parabola"]', 'en', '{"id":"q_projectile_1","prompt":"What is the shape of a projectile trajectory (ignoring air resistance)?","correctAnswer":"Parabola","type":"multiple_choice","options":["Circle","Parabola","Straight line","Spiral"],"hint":"Think of a ball thrown at an angle","explanation":"A projectile follows a parabolic path due to constant gravity acting downward."}'),

('physics_optics_reflection', 'Reflection and Mirrors', 'Physics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 10, 'PhysicsWallah', 1, 'optics', 'light_reflection', '["physics","optics","mirrors","reflection"]', 'en', '{"id":"q_optics_1","prompt":"The angle of incidence equals the angle of ___","correctAnswer":"Reflection","type":"fill_blank","options":[],"hint":"Law of Reflection","explanation":"The Law of Reflection states: angle of incidence = angle of reflection."}'),

('physics_electric_current', 'Ohm''s Law: V = IR', 'Physics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 14, 'ScienceGuy', 2, 'electricity', 'circuits', '["physics","electricity","ohm","current"]', 'en', '{"id":"q_ohm_1","prompt":"If voltage is 12V and resistance is 4 Ohms, what is the current?","correctAnswer":"3","type":"numerical","options":[],"hint":"V = I x R, so I = V / R","explanation":"Using Ohm''s law: I = V/R = 12/4 = 3 Amperes."}'),

-- CHEMISTRY (4 new)
('chem_chemical_bonding', 'Ionic vs Covalent Bonds', 'Chemistry', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 11, 'ChemPossible', 1, 'chemical_bonding', 'bond_types', '["chemistry","bonds","ionic","covalent"]', 'en', '{"id":"q_bonds_1","prompt":"NaCl (table salt) is an example of which type of bond?","correctAnswer":"Ionic bond","type":"multiple_choice","options":["Ionic bond","Covalent bond","Metallic bond","Hydrogen bond"],"hint":"A metal (Na) + a non-metal (Cl)","explanation":"NaCl forms an ionic bond through electron transfer from sodium to chlorine."}'),

('chem_acids_bases', 'Acids, Bases and pH Scale', 'Chemistry', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 13, 'ChemPossible', 2, 'acids_bases', 'ph_reactions', '["chemistry","acids","bases","ph","litmus"]', 'en', '{"id":"q_ph_1","prompt":"A solution with pH 3 is ___","correctAnswer":"Acidic","type":"multiple_choice","options":["Acidic","Basic","Neutral","Cannot determine"],"hint":"pH less than 7 means...","explanation":"pH below 7 indicates an acidic solution. pH 3 is strongly acidic."}'),

('chem_balancing_equations', 'How to Balance Chemical Equations', 'Chemistry', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 18, 'ChemPossible', 2, 'stoichiometry', 'balancing', '["chemistry","equations","balancing","stoichiometry"]', 'en', '{"id":"q_balance_1","prompt":"In H2 + O2 -> H2O, what coefficient goes before H2O when balanced?","correctAnswer":"2","type":"numerical","options":[],"hint":"Count hydrogen and oxygen atoms on both sides","explanation":"Balanced: 2H2 + O2 -> 2H2O. So coefficient for H2O is 2."}'),

('chem_mole_concept', 'The Mole Concept and Avogadro''s Number', 'Chemistry', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 16, 'ChemPossible', 3, 'mole_concept', 'quantitative_chemistry', '["chemistry","mole","avogadro","atoms"]', 'en', '{"id":"q_mole_1","prompt":"Avogadro''s number is approximately?","correctAnswer":"6.022 x 10^23","type":"multiple_choice","options":["6.022 x 10^23","3.14 x 10^23","6.022 x 10^20","1.602 x 10^-19"],"hint":"Number of particles in one mole","explanation":"One mole = 6.022 x 10^23 particles (Avogadro''s constant)."}'),

-- BIOLOGY (4 new)
('bio_photosynthesis', 'Photosynthesis: How Plants Make Food', 'Biology', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 12, 'BioBytes', 1, 'plant_biology', 'photosynthesis', '["biology","photosynthesis","plants","chlorophyll"]', 'en', '{"id":"q_photo_1","prompt":"Which pigment absorbs sunlight in photosynthesis?","correctAnswer":"Chlorophyll","type":"multiple_choice","options":["Melanin","Chlorophyll","Hemoglobin","Keratin"],"hint":"It gives leaves their green color","explanation":"Chlorophyll absorbs sunlight and gives plants their green color."}'),

('bio_dna_structure', 'DNA: The Double Helix', 'Biology', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 14, 'BioBytes', 2, 'genetics', 'dna_structure', '["biology","dna","genetics","double helix"]', 'en', '{"id":"q_dna_1","prompt":"Which base pairs with Adenine (A) in DNA?","correctAnswer":"Thymine (T)","type":"multiple_choice","options":["Guanine (G)","Thymine (T)","Cytosine (C)","Uracil (U)"],"hint":"A-T and G-C are complementary pairs","explanation":"In DNA, Adenine always pairs with Thymine, and Guanine pairs with Cytosine."}'),

('bio_human_heart', 'The Human Heart: 4 Chambers', 'Biology', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 10, 'BioBytes', 1, 'human_anatomy', 'circulatory_system', '["biology","heart","circulation","anatomy"]', 'en', '{"id":"q_heart_1","prompt":"Which chamber pumps oxygenated blood to the body?","correctAnswer":"Left Ventricle","type":"multiple_choice","options":["Right Atrium","Left Atrium","Right Ventricle","Left Ventricle"],"hint":"The most muscular chamber","explanation":"The left ventricle pumps oxygenated blood through the aorta to the entire body."}'),

('bio_ecosystem', 'Food Chains and Food Webs', 'Biology', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 13, 'BioBytes', 1, 'ecology', 'ecosystems', '["biology","ecology","food chain","ecosystem"]', 'en', '{"id":"q_eco_1","prompt":"Producers in a food chain are also called?","correctAnswer":"Autotrophs","type":"multiple_choice","options":["Heterotrophs","Autotrophs","Decomposers","Consumers"],"hint":"They make their own food","explanation":"Producers (autotrophs) make their own food through photosynthesis."}'),

-- MATHEMATICS (4 new)
('math_quadratic', 'Solving Quadratic Equations', 'Mathematics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 15, 'MathAntics', 2, 'algebra', 'quadratics', '["math","algebra","quadratic","equations"]', 'en', '{"id":"q_quad_1","prompt":"What are the roots of x^2 - 5x + 6 = 0?","correctAnswer":"2 and 3","type":"multiple_choice","options":["1 and 6","2 and 3","-2 and -3","3 and 4"],"hint":"Factor the equation","explanation":"(x-2)(x-3) = 0, so x = 2 and x = 3."}'),

('math_trigonometry', 'SOH-CAH-TOA: Trigonometric Ratios', 'Mathematics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 12, 'MathAntics', 2, 'trigonometry', 'trig_ratios', '["math","trigonometry","sine","cosine"]', 'en', '{"id":"q_trig_1","prompt":"sin(theta) = ?","correctAnswer":"Opposite / Hypotenuse","type":"multiple_choice","options":["Adjacent / Hypotenuse","Opposite / Hypotenuse","Opposite / Adjacent","Hypotenuse / Opposite"],"hint":"SOH: Sine = Opposite / Hypotenuse","explanation":"In a right triangle, sin(theta) = Opposite side / Hypotenuse."}'),

('math_probability_basics', 'Probability: Coin Flips and Dice', 'Mathematics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 10, 'MathAntics', 1, 'probability', 'basic_probability', '["math","probability","dice","coin"]', 'en', '{"id":"q_prob_1","prompt":"What is the probability of rolling a 6 on a fair die?","correctAnswer":"1/6","type":"multiple_choice","options":["1/2","1/3","1/6","1/12"],"hint":"A die has 6 faces","explanation":"Each face has equal probability: P(6) = 1/6."}'),

('math_calculus_limits', 'Introduction to Limits', 'Mathematics', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 18, 'MathAntics', 3, 'calculus', 'limits', '["math","calculus","limits"]', 'en', '{"id":"q_limits_1","prompt":"What is the limit of (x^2-1)/(x-1) as x approaches 1?","correctAnswer":"2","type":"numerical","options":[],"hint":"Factor the numerator: x^2-1 = (x+1)(x-1)","explanation":"(x^2-1)/(x-1) = (x+1)(x-1)/(x-1) = x+1. At x=1, this equals 2."}'),

-- HISTORY (4 new)
('hist_independence', 'Indian Independence Movement: Key Events', 'History', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 15, 'HistoryHub', 1, 'indian_history', 'freedom_struggle', '["history","india","independence","gandhi"]', 'en', '{"id":"q_hist_1","prompt":"In which year did India gain independence from British rule?","correctAnswer":"1947","type":"numerical","options":[],"hint":"15th August...","explanation":"India gained independence on 15th August 1947."}'),

('hist_world_war_2', 'World War II: Causes and Consequences', 'History', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 20, 'HistoryHub', 2, 'world_history', 'world_wars', '["history","ww2","world war","allies"]', 'en', '{"id":"q_ww2_1","prompt":"Which event triggered World War II in Europe?","correctAnswer":"Germany''s invasion of Poland","type":"multiple_choice","options":["Treaty of Versailles","Germany''s invasion of Poland","Pearl Harbor","Russian Revolution"],"hint":"September 1, 1939","explanation":"Germany invaded Poland on September 1, 1939, leading Britain and France to declare war."}'),

('hist_mughal_empire', 'The Mughal Empire: Rise and Fall', 'History', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 14, 'HistoryHub', 2, 'indian_history', 'mughal_dynasty', '["history","mughals","akbar","india"]', 'en', '{"id":"q_mughal_1","prompt":"Which Mughal emperor built the Taj Mahal?","correctAnswer":"Shah Jahan","type":"multiple_choice","options":["Akbar","Shah Jahan","Aurangzeb","Babur"],"hint":"Built in memory of his wife Mumtaz Mahal","explanation":"Shah Jahan built the Taj Mahal in Agra as a mausoleum for his wife Mumtaz Mahal."}'),

('hist_french_revolution', 'The French Revolution: Liberty, Equality, Fraternity', 'History', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 16, 'HistoryHub', 2, 'world_history', 'revolutions', '["history","france","revolution","democracy"]', 'en', '{"id":"q_french_1","prompt":"The storming of which prison marked the beginning of the French Revolution?","correctAnswer":"Bastille","type":"multiple_choice","options":["Versailles","Bastille","Louvre","Notre-Dame"],"hint":"July 14, 1789 - now a national holiday in France","explanation":"The storming of the Bastille on July 14, 1789 symbolized the fall of royal authority."}')

ON CONFLICT (id) DO NOTHING;

-- Verify the results
SELECT subject, COUNT(*) as count FROM educational_content GROUP BY subject ORDER BY subject;
