-- Gamification Schema

-- 1. User Streaks
create table public.user_streaks (
  user_id uuid references auth.users not null primary key,
  current_streak int default 0,
  max_streak int default 0,
  today_reps int default 0,
  last_rep_date timestamptz,
  completed_days text[] default '{}', -- array of ISO date strings for simplicity
  synced_at timestamptz default now()
);

-- 2. User XP
create table public.user_xp (
  user_id uuid references auth.users not null primary key,
  total_xp int default 0,
  current_level int default 1,
  xp_for_next_level int default 100,
  synced_at timestamptz default now()
);

-- 3. User Achievements
create table public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_id text not null,
  is_unlocked boolean default false,
  progress numeric default 0.0,
  unlocked_at timestamptz,
  synced_at timestamptz default now(),
  unique(user_id, achievement_id)
);

-- RLS
alter table public.user_streaks enable row level security;
alter table public.user_xp enable row level security;
alter table public.user_achievements enable row level security;

-- Policies
create policy "Users can view their own streaks" on public.user_streaks for select to authenticated using ( auth.uid() = user_id );
create policy "Users can update their own streaks" on public.user_streaks for all to authenticated using ( auth.uid() = user_id );

create policy "Users can view their own xp" on public.user_xp for select to authenticated using ( auth.uid() = user_id );
create policy "Users can update their own xp" on public.user_xp for all to authenticated using ( auth.uid() = user_id );

create policy "Users can view their own achievements" on public.user_achievements for select to authenticated using ( auth.uid() = user_id );
create policy "Users can update their own achievements" on public.user_achievements for all to authenticated using ( auth.uid() = user_id );
