-- Social Features and True Multiplayer Schema

-- 1. User Followers (Friends System)
CREATE TABLE public.user_followers (
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  created_at timestamptz default now(),
  primary key (follower_id, following_id)
);

-- 2. Video Comments
CREATE TABLE public.educational_comments (
  id bigint generated by default as identity primary key,
  video_id text references public.educational_content(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  body text not null,
  likes_count int default 0,
  created_at timestamptz default now()
);

-- 3. Study Squads (Clans)
CREATE TABLE public.study_squads (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  avatar_url text,
  weekly_goal int default 500,
  created_by uuid references auth.users not null,
  created_at timestamptz default now()
);

-- 4. Squad Members
CREATE TABLE public.squad_members (
  squad_id bigint references public.study_squads(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'member' check (role in ('admin', 'member')),
  joined_at timestamptz default now(),
  primary key (squad_id, user_id)
);

-- Enable RLS
ALTER TABLE public.user_followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.educational_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_squads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.squad_members ENABLE ROW LEVEL SECURITY;

-- Policies for user_followers
CREATE POLICY "Followers are viewable by everyone" 
ON public.user_followers FOR SELECT TO public 
USING (true);

CREATE POLICY "Users can follow others" 
ON public.user_followers FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow" 
ON public.user_followers FOR DELETE TO authenticated 
USING (auth.uid() = follower_id);

-- Policies for educational_comments
CREATE POLICY "Comments are viewable by everyone" 
ON public.educational_comments FOR SELECT TO public 
USING (true);

CREATE POLICY "Users can add comments" 
ON public.educational_comments FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments" 
ON public.educational_comments FOR DELETE TO authenticated 
USING (auth.uid() = user_id);

-- Policies for squads
CREATE POLICY "Squads are viewable by everyone" 
ON public.study_squads FOR SELECT TO public 
USING (true);

CREATE POLICY "Users can create squads" 
ON public.study_squads FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = created_by);

-- Policies for squad members
CREATE POLICY "Squad members are viewable by everyone" 
ON public.squad_members FOR SELECT TO public 
USING (true);

CREATE POLICY "Users can join squads" 
ON public.squad_members FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = user_id);
