-- 1. educational_content Table (Metadata)
create table if not exists public.educational_content (
  id uuid default gen_random_uuid() primary key,
  "videoUrl" text not null,
  "lockTimestamp" int not null,
  "question" jsonb not null,
  "creatorName" text default 'StudyReps',
  "creatorAvatar" text,
  "title" text not null,
  "subject" text not null,
  "thumbnailUrl" text,
  "likesCount" int default 0,
  "repsCompleted" int default 0,
  "duration" bigint default 0,
  "transcript" text,
  "tags" text[],
  "prerequisiteIds" text[],
  "difficultyLevel" int default 1,
  "topicId" text,
  "conceptCluster" text,
  "language" text default 'en',
  created_at timestamptz default now()
);

-- 2. educational_likes Table
create table if not exists public.educational_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id uuid references public.educational_content (id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, video_id)
);

-- 3. educational_saves Table
create table if not exists public.educational_saves (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id uuid references public.educational_content (id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, video_id)
);

-- 4. educational_views Table
create table if not exists public.educational_views (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  video_id uuid references public.educational_content (id) on delete cascade not null,
  viewed_at timestamptz default now()
);

-- 5. educational_shares Table (NEW)
create table if not exists public.educational_shares (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  video_id uuid references public.educational_content (id) on delete cascade not null,
  shared_at timestamptz default now(),
  platform text -- Optional: 'whatsapp', 'copy_link' etc.
);

-- Enable RLS
alter table public.educational_content enable row level security;
alter table public.educational_likes enable row level security;
alter table public.educational_saves enable row level security;
alter table public.educational_views enable row level security;
alter table public.educational_shares enable row level security;

-- Policies
create policy "Public content are viewable by everyone" on public.educational_content for select to public using ( true );
create policy "Likes viewable by everyone" on public.educational_likes for select to public using ( true );
create policy "Users can insert their own likes" on public.educational_likes for insert to authenticated with check ( auth.uid() = user_id );
create policy "Users can delete their own likes" on public.educational_likes for delete to authenticated using ( auth.uid() = user_id );
create policy "Users can view their own saves" on public.educational_saves for select to authenticated using ( auth.uid() = user_id );
create policy "Users can insert their own saves" on public.educational_saves for insert to authenticated with check ( auth.uid() = user_id );
create policy "Users can delete their own saves" on public.educational_saves for delete to authenticated using ( auth.uid() = user_id );
create policy "Users can insert views" on public.educational_views for insert to public with check ( true );
create policy "Users can insert shares" on public.educational_shares for insert to public with check ( true );
